server:
  port: 8083
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

booking:
  service:
    url: http://localhost:8082/api/v1/bookings